# Stage 1: Install dependencies
FROM python:3.9-slim AS builder

WORKDIR /app

RUN python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


# Stage 2: Runtime image
FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY data_analysis.py .
COPY All_Diets.csv .

CMD ["python", "data_analysis.py"]